EXCEL_PATH = r"D:\tax\诉求分析25年\【省局导出】2025年全市12366工单.xls"
SAVE_PATH = r"D:\tax\诉求分析25年\output_12366.xlsx"
OUTPUT_DIR = r"D:\tax\诉求分析25年\OUTPUT"
FINAL_DIR = r"D:\tax\诉求分析25年\OUTPUT\最终结果4.xlsx"
EMBEDDING_MODEL_NAME = "BAAI/bge-large-zh-v1.5"
DATA_COLUMN = "Extracted_Content"
STATE_FILE = r"D:\tax\诉求分析25年\OUTPUT\tax_analysis_checkpoint5.pkl"
TEST_FILE = r"D:\tax\诉求分析25年\最终完整汇报表2.xlsx"